url: "https://typo3.pp.ua"
baseurl: ""
encoding: UTF-8
timezone: Europe/Kyiv
title: Site Title
description: Site Description
name: Site Name
brand: Site Brand
logo: "/images/logo.svg"
author:
  name: Василь Мосійчук
  email: typo3@ukr.net
plugins:
  - jekyll-feed
  - jekyll-sitemap
