url: "https://typo3.pp.ua"
baseurl: ""
encoding: UTF-8
timezone: Europe/Kyiv
title: TYPO3 CMS Integrator in Ukraine
description: Description about TYPO3 CMS Integrator in Ukraine
name: TYPO3 CMS Інтегратор в Україні
brand: pp.ua
logo: "/images/logo.svg"
author:
  name: Василь Мосійчук
  email: typo3@ukr.net
plugins:
  - jekyll-feed
  - jekyll-sitemap
