url: "https://typo3.pp.ua"
baseurl: ""
encoding: UTF-8
timezone: Europe/Kyiv
title: Site Title
description: Site Description
name: Site Name
brand: Site Brand
logo: "/images/logo.svg"
author:
  name: Василь Мосійчук
  website: http://www.vasyl.net
sass:
  style: compact
plugins:
  - jekyll-feed
  - jekyll-sitemap
