# Site settings
url: "https://typo3.pp.ua"
baseurl: ""
encoding: UTF-8
lang: uk_UA
timezone: Europe/Kyiv
title: Site Title
description: Site Description
name: Site Name
brand: Site Brand
logo: "/assets/images/logo.svg"
author:
  name: Василь Мосійчук
  website: http://www.vasyl.net
# Build settings
#sass:
#  style: compact
#defaults:
#  - scope:
#      path: "/assets/images"
#    values:
#      image: true
#plugins:
#  - jekyll-feed
#  - jekyll-sitemap
exclude:
  - README.md
