# Site settings
url: "https://www.typo3.pp.ua"
baseurl: ""
encoding: UTF-8
lang: uk_UA
timezone: Europe/Kiev
title: Ради в Івано-Франківській області
description: Представни́цькі органи влади Івано-Франківської області
name: Місцеві ради
brand: Рада
logo: "/assets/images/logo.svg"
author:
  name: Vasyl&nbsp;Mosiychuk
  website: http://www.vasyl.net
  email: info@vasyl.net
developer:
  name: vasyl.net
  website: http://www.vasyl.net
  email: info@vasyl.net

contact:
  name: Вебсайт представни́цьких органів&nbsp;влади
  address: 76018, м. Івано-Франківськ, вул.&nbsp;С.&nbsp;Стрільців,&nbsp;56
  phone_main: (067) 433 00 66
  phone_hot:  (050) 000 00 00
  phone_fax:  (034) 200 00 00
  email: info@rada.if.ua
  www: http://www.rada.if.ua/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: /*/decisions/
      type: "decisions"
    values:
      layout: "decisions"
  - scope:
      path: /*/news/
      type: "news"
    values:
      layout: "news"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - README.md
