# Site settings
url: "https://www.typo3.pp.ua"
baseurl: ""
encoding: UTF-8
lang: uk_UA
timezone: Europe/Kiev
title: Default Site Title
description: Default Site Description
name: Site Name
brand:
logo: "/assets/images/logo.svg"
author:
  name: Vasyl&nbsp;Mosiychuk
  website: http://www.vasyl.net

legal:
  name: Вебсайт представни́цьких органів&nbsp;влади
  address: 76018, м. Івано-Франківськ, вул.&nbsp;С.&nbsp;Стрільців,&nbsp;56
  phone:
    main: (067) 433 00 66
    hot:  (050) 000 00 00
    fax:  (034) 200 00 00
  email: info@rada.if.ua
  www: http://www.rada.if.ua/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: /*/decisions/
      type: "decisions"
    values:
      layout: "decisions"
  -
    scope:
      path: /*/news/
      type: "news"
    values:
      layout: "news"
  -
    scope:
      path: "assets/images"
    values:
      image: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"


exclude:
  - README.md
