name: TYPO3 CMS Інтегратор в Україні
brand: pp.ua
title: TYPO3 CMS Integrator in Ukraine
description: Description about TYPO3 CMS Integrator in Ukraine
encoding: UTF-8
baseurl: ""
url: "https://typo3.pp.ua"
timezone: Europe/Kyiv
logo: "/images/logo.svg"
author:
  name: Василь Мосійчук
  email: typo3@ukr.net
plugins:
  - jekyll-feed
  - jekyll-sitemap
