name: TYPO3 CMS Інтегратор в Україні
title: TYPO3 CMS Integrator in Ukraine
description: Description about TYPO3 CMS Integrator in Ukraine
baseurl: ""
url: "https://typo3.pp.ua"
timezone: Europe/Ukraine
logo: "/images/logo.png"
author:
  name: Василь Мосійчук
  email: typo3@ukr.net
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
